# The URL the site will be built for
base_url = "https://ageof.info"

# Used in RSS by default
title = "ageof.info - the blog of elias julian marko garcia"
description = "placeholder text for now"

# The default language, used in RSS
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# taxonomies = [
#            {name = "tags"},
#            {name = "categories"}
# ]

[extra]

author = "elias"
# Put all your custom variables here

# ---------------------------------------------------------
# Configurations taken directly from Terminal's config.toml
# 
# I will be commenting configs in and out as I figure out
# how to interact with them correctly.
# ---------------------------------------------------------

# [params]

# dir name of your blog content (default is `content/posts`)
content_type_name = "posts"
# ["orange", "blue", "red", "green", "pink"]
theme_color = "orange"
# if you set this to 0, only submenu trigger will be visible
show_menu_items = 2
# set theme to full screen width
full_width = false
# center theme with default width
center = false
# set a custom favicon (default is a `themeColor` square)
# favicon = "favicon.ico"

# [languages]
#   [languages.en]
#     title = "ageof.info"
#     subtitle = "A simple, retro theme for Hugo"
#     keywords = ""
copyright = "copyright notice here"
#     menuMore = "Show more"
#     readMore = "Read more"
#     readOtherPosts = "Read other posts"'

    # [languages.en.params.logo]
logo_text = "$ ~/info.txt"
logo_home_link = "/"

main_menu = [
              {url="$BASE_URL/about", name="About"},
              {url="$BASE_URL/contact", name="Contact"},
              {url="$BASE_URL/foo", name="foo"},
]
menu_more = "Show more"
read_more = "Read more"
read_other_posts = "Read other posts"
    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     url = "/about"
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"
